# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampleQuadraticMVTcpp <- function(init, mean, precision, threshold, nSamples, burnin, trim) {
    .Call('PSAT_sampleQuadraticMVTcpp', PACKAGE = 'PSAT', init, mean, precision, threshold, nSamples, burnin, trim)
}

quadraticRobinsMonroe <- function(var, upper, alpha, observed, initU, threshold, sqrtTestMat, invSqrtTestMat, sampPrecision, stepSize, burnin, mhiters, rbIters) {
    .Call('PSAT_quadraticRobinsMonroe', PACKAGE = 'PSAT', var, upper, alpha, observed, initU, threshold, sqrtTestMat, invSqrtTestMat, sampPrecision, stepSize, burnin, mhiters, rbIters)
}

sampleLogisticCpp <- function(y, X, Xy, Xp, probs, beta, intercept, testMat, threshold, nSamples, burnin, trim, returnY) {
    .Call('PSAT_sampleLogisticCpp', PACKAGE = 'PSAT', y, X, Xy, Xp, probs, beta, intercept, testMat, threshold, nSamples, burnin, trim, returnY)
}

